### ISSUE TITLE
Arguments dismatch

### ISSUE THREAD

**Issue by Liforam** [JannerM/intrinsics-network#6] opened 2018-04-02 05:57 UTC
Traceback (most recent call last):
  File "shader.py", line 50, in <module>
    pipeline.visualize_shader(shader, val_loader, save_path )
  File "/home/xuwh/xu/intrinsics-network-master/pipeline/visualization.py", line 52, in visualize_shader
    grid = torchvision.utils.make_grid(images, nrow=3, padding=0).cpu().numpy().transpose(1,2,0)
  File "/home/xuwh/.local/lib/python2.7/site-packages/torchvision/utils.py", line 35, in make_grid
    tensor = torch.stack(tensor, dim=0)
  File "/home/xuwh/.local/lib/python2.7/site-packages/torch/functional.py", line 58, in stack
    return torch.cat(inputs, dim)
TypeError: cat received an invalid combination of arguments - got (list, int), but expected one of:
 * (sequence[torch.cuda.FloatTensor] seq)
 * (sequence[torch.cuda.FloatTensor] seq, int dim)
      didn't match because some of the arguments have invalid types: (list, int)

Any solution? Thanks in advance. @JannerM  @FangYang970206  @Nighteye

**Comment by jannerm** [comment] 2018-07-23 07:56
I can't reproduce with the torch version this repo was developed with (0.1.12_2). What python / torch version are you using?

**Comment by jannerm** [comment] 2018-07-23 08:11
I was able to get this error using python 2.7 and torch 0.3.0. It turns out the targets were FloatTensors, but the inputs and predictions were CudaTensors, and for some reason this didn't matter in torch 0.1.12. This is now fixed.

**Closed as completed** 2018-07-23 08:11 UTC
